import json
from pathlib import Path

ROOT = Path(__file__).parent
EVAL = ROOT / 'evaluation' / 'gift-cards-batch-100'
r = json.loads((EVAL / 'emotion_comparison.json').read_text(encoding='utf-8'))
emotions = ['anger','anticipation','disgust','fear','joy','sadness','surprise','trust']
llm = r['llm_distribution']; lex = r['lexicon_distribution_including_no_match']
def esc(s):
    return str(s).replace('&','&amp;').replace('<','&lt;').replace('>','&gt;').replace('"','&quot;').replace("'",'&#39;')
barrows = ''.join('<div class="barrow"><div>%s</div><div class="bars"><div class="bar llm" style="width:%s%%"></div><div class="bar lex" style="width:%s%%"></div></div><div class="nums">%s / %s</div></div>' % (e, llm.get(e,0)/max(llm.values())*100, lex.get(e,0)/max(lex.values())*100, llm.get(e,0), lex.get(e,0)) for e in emotions)
conf = ''.join('<tr><th>%s</th>%s</tr>' % (e, ''.join('<td>%s</td>' % r['confusion_matrix_llm_rows_lexicon_columns'][e][x] for x in emotions)) for e in emotions)
items = r['disagreements'] + r['no_match_examples']
rows = ''.join('<tr><td>#%s</td><td><strong>%s</strong></td><td><span class="tag %s">%s</span></td><td><span class="tag %s">%s</span></td><td>%s</td><td><small>%s</small></td></tr>' % (x['id'],esc(x['title']),x['llm_emotion'],x['llm_emotion'],x['lexicon_emotion'] or 'none',x['lexicon_emotion'] or 'no match','—' if x['emotion_agreement'] is None else ('✓ agree' if x['emotion_agreement'] else '✕ diverge'),esc(', '.join(x['matched_words'][:14]))) for x in items)
template = '''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Emotion methods comparison</title><style>
:root{--bg:#f4f6f2;--surface:#fff;--ink:#17221b;--muted:#657168;--line:#d7dfd7;--accent:#277653;--orange:#b36a32}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.45 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}main{max-width:1120px;margin:auto;padding:34px 24px 60px}.kicker{color:var(--accent);font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}h1{font-size:clamp(30px,4vw,50px);line-height:1.02;letter-spacing:-.055em;margin:8px 0 12px}h2{font-size:19px;margin:0 0 4px}.lede,.note{color:var(--muted)}.lede{max-width:760px;margin:0 0 25px}.cards{display:grid;grid-template-columns:1.15fr 1fr 1fr 1fr;gap:1px;background:var(--line);border:1px solid var(--line);margin:24px 0}.card{background:var(--surface);padding:20px}.card:first-child{background:var(--accent);color:#fff}.value{display:block;font-size:31px;font-weight:800;letter-spacing:-.05em}.label{font-size:12px;color:var(--muted)}.card:first-child .label{color:#d9ede1}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.panel{background:var(--surface);border:1px solid var(--line);padding:20px;box-shadow:0 10px 28px #1b33220d;margin-top:16px}.barrow{display:grid;grid-template-columns:105px 1fr 70px;align-items:center;gap:10px;margin:14px 0}.bars{display:grid;gap:4px}.bar{height:10px;min-width:2px}.bar.llm{background:var(--accent)}.bar.lex{background:var(--orange)}.nums{text-align:right;color:var(--muted);font-size:12px}.legend{font-size:11px;color:var(--muted)}.matrix-wrap{overflow:auto}.matrix{border-collapse:collapse;font-size:11px;width:100%}.matrix th,.matrix td{border:1px solid var(--line);padding:7px;text-align:center;min-width:34px}.matrix th{color:var(--muted)}.audit{width:100%;border-collapse:collapse}.audit th,.audit td{border-top:1px solid var(--line);padding:10px 6px;text-align:left;vertical-align:top}.audit th{font-size:10px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted)}.tag{display:inline-block;padding:3px 7px;border-radius:99px;font-size:10px;font-weight:800;background:#eef2ee}.joy,.trust{color:#236746;background:#e4f2e9}.anticipation{color:#85501f;background:#faeddc}.anger,.sadness,.disgust,.fear{color:#963c36;background:#f9e8e5}.surprise{color:#5b4b93;background:#eee9fb}.none{color:var(--muted)}.callout{padding:12px 14px;background:#fff9ed;border-left:3px solid var(--orange);color:#60431d;margin-top:16px}footer{color:var(--muted);font-size:11px;margin-top:22px}@media(max-width:800px){main{padding:25px 15px}.cards,.grid{grid-template-columns:1fr}.card:first-child{grid-column:auto}} 
</style></head><body><main><div class="kicker">Amazon Gift Cards · emotion analysis</div><h1>Two lenses on one review</h1><p class="lede">The LLM reads context and selects a primary emotion. The NRC method counts emotion-associated words. They are independent signals, not interchangeable ground truth.</p><div class="cards"><div class="card"><span class="value">__AGREE__%</span><span class="label">agreement where lexicon matched · __AGREE_N__ / __COMPARED__</span></div><div class="card"><span class="value">__NOMATCH__</span><span class="label">lexicon no-match reviews</span></div><div class="card"><span class="value">__DIVERGE__</span><span class="label">compared divergences</span></div><div class="card"><span class="value">__ALL__%</span><span class="label">agreement across all 100</span></div></div><div class="grid"><section class="panel"><h2>Emotion distribution</h2><p class="note">Each row shows LLM count / NRC count. Bars use each method's own scale.</p>__BARROWS__<p class="legend"><span class="bar llm" style="display:inline-block;width:12px"></span> LLM &nbsp; <span class="bar lex" style="display:inline-block;width:12px"></span> NRC lexicon</p><div class="callout"><strong>Largest divergence:</strong> NRC assigns anticipation to 59 reviews, while the LLM favors joy (48) and trust (42). Word counts reward generic words such as “expect” or “arrive”; the LLM can use overall context.</div></section><section class="panel"><h2>Agreement matrix</h2><p class="note">LLM emotions are rows; NRC emotions are columns. Only the 85 lexicon-matched reviews are included.</p><div class="matrix-wrap"><table class="matrix"><thead><tr><th>LLM ↓ / NRC →</th>__HEADERS__</tr></thead><tbody>__CONF__</tbody></table></div><p class="note">The diagonal totals 19 agreements. No-match reviews are excluded here.</p></section></div><section class="panel"><h2>Evidence: divergences and no-match cases</h2><p class="note">__ITEMS__ rows are shown so the comparison can be audited. Matched words are lexicon evidence, not explanations of LLM decisions.</p><div style="overflow:auto"><table class="audit"><thead><tr><th>Row</th><th>Title</th><th>LLM</th><th>NRC</th><th>Result</th><th>Matched words</th></tr></thead><tbody>__ROWS__</tbody></table></div></section><footer>N=100, first records in file order. NRC Emotion Lexicon v0.92; title and text tokenized with the documented ASCII-word regex. Ties use the fixed emotion order; zero matches returns no match.</footer></main></body></html>'''
headers=''.join('<th>%s</th>' % e[:4] for e in emotions)
html=template.replace('__AGREE__',str(r['agreement_rate']*100)).replace('__AGREE_N__',str(r['agreement_count'])).replace('__COMPARED__',str(r['compared_n'])).replace('__NOMATCH__',str(r['lexicon_no_match'])).replace('__DIVERGE__',str(r['disagreement_count'])).replace('__ALL__',str(r['agreement_rate_all_rows_treating_no_match_as_disagreement']*100)).replace('__BARROWS__',barrows).replace('__HEADERS__',headers).replace('__CONF__',conf).replace('__ITEMS__',str(len(items))).replace('__ROWS__',rows)
out=EVAL/'emotion-comparison.html'; out.write_text(html,encoding='utf-8'); print(f'Wrote {out} ({out.stat().st_size} bytes).')
